# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_us__company_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_us_',
            old_name='year',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='about_us_',
            name='detail',
        ),
    ]
