# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160114_0637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us_',
            new_name='About_us',
        ),
    ]
