# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:37
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='000', help_text='포스팅 제목을 100자 이내로 써주세요.', max_length=100, validators=[blog.models.min_length_validator]),
        ),
    ]
