# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 08:52
from __future__ import unicode_literals

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone',
            field=blog.models.PhoneField(blank=True, max_length=11),
        ),
    ]
