# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160129_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog/post'),
        ),
    ]
